### ISSUE TITLE
Licence of drivers

### ISSUE THREAD

**Issue by DavidLutton** [pyvisa/pyvisa-drivers#2]
As I understand it, software with no defined license is essentially unusable
See [Choose a License - No License](https://choosealicense.com/no-permission/)

Should there be a default unless otherwise specified?
Like MIT given that PyVISA projects use it and that licence compatibility is helpful  

How should the licence of drivers be demonstrated?
By way of a licence in each _driver.py_ or _driver/LICENCE.txt_

The Keysight PNA driver is probably BSD 3 clause given the licence of the upstream project

**Comment by dvincentwest** [comment]
Thanks for that observation.  I believe that philosophy is the correct one, a global license that matches the pyvisa license with sub licenses possible for individual drivers based on the requirements of the contributer.  I will contact Alex to discuss the preferred license of the keysight_pna module

@MatthieuDartiailh do you have any comment?

**Comment by MatthieuDartiailh** [comment]
No comment on my part, such save that to say that if the driver uses a different license it should be mentioned at the top of the file. We may keep copy of the different license in the repo for reference if needs be.

**Comment by dvincentwest** [comment]
should be fixed with #3 .  I cleared distribution of the skrf driver with Alex here.  License and copyright are not a concern for him, so nothing additional needed.
